import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import About from "../components/About"
import Habilidades from "../components/Habilidades"
import Proyectos from "../components/Proyectos"
import Contacto from "../components/Contacto"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eduardo | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <About />
      <Habilidades />
      <Proyectos />
      <Contacto />
    </div>
  )
}
